#!/bin/bash

INPUT="/home/sci/ssane/data/DoubleGyre/DoubleGyre_TimeVarying_0_to_11.vtk"
DIMX=256
DIMY=128
DIMZ=1101

SDIMX=256
SDIMY=128

OUTPUT="Uncertainty_1_1.vtk"
ITERATIONS=10
NUM_STEPS_PER_ITERATION=100

OFFSET="0.000001"
EXPONENT="1"
MINIMUM_VAL="1"
INFLATE="100"

./GenerateUncertaintyFMs $INPUT $DIMX $DIMY $DIMZ $SDIMX $SDIMY $OUTPUT $ITERATIONS $NUM_STEPS_PER_ITERATION $OFFSET $EXPONENT $MINIMUM_VAL $INFLATE
