#!/bin/bash

INPUT="/home/sci/ssane/data/DoubleGyre/DoubleGyre_TimeVarying_0_to_11.vtk"
DIMX=256
DIMY=128
DIMZ=1101

SDIMX=32
SDIMY=16

OUTPUT="Entropy_1_64.vtk"
ITERATIONS=10
NUM_STEPS_PER_ITERATION=100

OFFSET="0.000001"
EXPONENT="2"
MINIMUM_VAL="0.5"
INFLATE="1"
NEIGHBORHOOD="13"

./GenerateEntropyFMs $INPUT $DIMX $DIMY $DIMZ $SDIMX $SDIMY $OUTPUT $ITERATIONS $NUM_STEPS_PER_ITERATION $OFFSET $EXPONENT $MINIMUM_VAL $INFLATE $NEIGHBORHOOD
